---
# Bjoern Teipel <bjoern.teipel@rackspace.com>
#
# Play to tear down Swift data nodes
#
# WARNING: This playbook will stop the swift services on the swift_obj server group and unmount/reformat/remount the XFS disks
#          mounted under /srv/node. If there is no disk mounted, the play will not execute any tasks.
#
#                                 !!!!! DATA WILL BE DELETED WHEN RUNNING THIS PLAY !!!!!
#
# Overrides:
# - xfs_inode_size defaults to 1024 and is used for the -i parameter with mkfs.xfs
# - xfs_mount_options default to rw,noatime,nobarrier,logbufs=8,noquota
# - xfs_format_options defaults to ""
#
# Run it:
# openstack-ansible swift-datacrusher.yml
#
# Options can be overridden with passing these arguments to openstack-ansible:
# openstack-ansible swift-datacrusher.yml -exfs_inode_size=256 -exfs_format_options='-linternal'

- name: Please remove me, I'm just a fail safe
  please-remove-me-before-crushing-swift-and-you-know-what-you-are-doing:

- name: Register mountpoints
  hosts: swift_obj
  tasks:
    - shell: |
        awk '/\/srv\/node/ { split($2,i,"/"); print $1 "," i[4] }' /proc/mounts
      register: swift_drives

- name: Stop Swift Services
  hosts: swift_obj
  tasks:
    - service:
        name: "{{ item }}"
        state: stopped
      with_items:
        - "swift-account-server"
        - "swift-container-server"
        - "swift-object-server"
      when: "'disk1' in swift_drives.stdout"

- name: Unmount Swift disks
  hosts: swift_obj
  tasks:
    - shell: |
        umount -f /srv/node/{{ item.split(',')[1] }}
      with_items: swift_drives.stdout_lines
      when: swift_drives.stdout_lines|length > 0

- name: Format Swift disk
  hosts: swift_obj
  tasks:
    - shell: |
        mkfs.xfs -L {{ item.split(',')[1] }} -f -i size={{ xfs_inode_size |default('1024') | int }} {{ xfs_format_options |default('') }} {{ item.split(',')[0] }}
      with_items: swift_drives.stdout_lines
      when: swift_drives.stdout_lines|length > 0

- name: Mount Swift disks
  hosts: swift_obj
  tasks:
    - mount:
        name: "/srv/node/{{ item.split(',')[1] }}"
        src: "LABEL={{ item.split(',')[1] }}"
        fstype: xfs
        opts: "{{ xfs_mount_options |default('rw,noatime,nobarrier,logbufs=8,noquota') }}"
        state: mounted
      with_items: swift_drives.stdout_lines
      when: swift_drives.stdout_lines|length > 0

- name: Start Swift Services
  hosts: swift_obj
  tasks:
    - service:
        name: "{{ item }}"
        state: started
      with_items:
        - "swift-account-server"
        - "swift-container-server"
        - "swift-object-server"
      register: swift_object_server
      when: "'disk1' in swift_drives.stdout"
