---
# Bjoern Teipel <bjoern.teipel@rackspace.com>
#
# Play to tear down Swift data nodes
#
# WARNING: This playbook will stop the swift services on the swift_obj server group and unmount/reformat/remount the XFS disks
#          mounted under /srv/node. If there is no disk mounted, the play will not execute any tasks.
#
#                                 !!!!! DATA WILL BE DELETED WHEN RUNNING THIS PLAY !!!!!
#
# Overrides:
# - xfs_inode_size defaults to 1024 and is used for the -i parameter with mkfs.xfs
# - xfs_mount_options default to rw,noatime,nodiratime,nobarrier,logbufs=8,noquota
# - xfs_format_options defaults to ""
# - exclude_drive_labels defaults to ""
# - exclude_drive_labels_format_option to ""
#
# Run it:
# openstack-ansible swift-datacrusher.yml
#
# Options can be overridden with passing these arguments to openstack-ansible:
# openstack-ansible swift-datacrusher.yml -e xfs_inode_size=256 -e xfs_format_options='-linternal' -e exclude_drive_labels="disk1,disk2" -e exclude_drive_labels_format_option="disk3,disk4"

- name: Please remove me, I'm just a fail safe
  please-remove-me-before-crushing-swift-and-you-know-what-you-are-doing:

- name: Register mountpoints
  hosts: swift_obj
  tasks:
    #For active XFS mounts: awk '/\/srv\/node/ { split($2,i,"/"); print $1 "," i[4] }' /proc/mounts
    #For any XFS mount: blkid |awk '/TYPE="xfs/ { split($0,blkid,"\n"); for (n in blkid) { if (substr(blkid[n],0,5) == "/dev/") { device=$1; pos=match(blkid[n],"LABEL="); if (pos > 0) { str=device","substr(blkid[n],pos+7,6); gsub(":|\"","",str); print str } } } }'
    - shell: |
        blkid |awk '/TYPE="xfs/ { split($0,blkid,"\n"); for (n in blkid) { if (substr(blkid[n],0,5) == "/dev/") { device=$1; pos=match(blkid[n],"LABEL="); if (pos > 0) { str=device","substr(blkid[n],pos+7,6); gsub(":|\"","",str); print str } } } }'
      register: swift_drives
      tags:
        - "always"
        - "register_drives"

- name: Stop Swift Services
  hosts: swift_obj
  tasks:
    - service:
        name: "{{ item }}"
        state: stopped
      with_items:
        - "swift-object-server"
        - "swift-object-replicator"
        - "swift-container-reconciler"
        - "swift-object-expirer"
        - "swift-object-updater"
        - "swift-object-auditor"
        - "swift-container-server"
        - "swift-container-replicator"
        - "swift-container-updater"
        - "swift-container-auditor"
        - "swift-account-server"
        - "swift-account-replicator"
        - "swift-account-reaper"
        - "swift-account-auditor"
        - "swift-container-sync"
        - "rsync"
      tags:
        - "service-stop"
        - "service-restart"
        - "remount"

- name: Unmount Swift disks
  hosts: swift_obj
  tasks:
    - shell: |
        umount -f /srv/node/{{ item.split(',')[1] }}
      with_items: swift_drives.stdout_lines
      when:
        - "{{ swift_drives.stdout_lines | length > 0 }}"
        - "{{ item.split(',')[1] not in ( exclude_drive_labels | default ({}) ) }}"
      tags:
        - "remount"
        - "umount"

- name: Format Swift disk
  hosts: swift_obj
  tasks:
    - shell: |
        mkfs.xfs -L {{ item.split(',')[1] }} -f -i size={{ xfs_inode_size |default('1024') | int }} {{ xfs_format_options |default('') }} {{ item.split(',')[0] }}
      with_items: swift_drives.stdout_lines
      when:
        - "{{ swift_drives.stdout_lines | length > 0 }}"
        - "{{ item.split(',')[1] not in ( exclude_drive_labels | default ({}) ) }}"
        - "{{ item.split(',')[1] not in ( exclude_drive_labels_format_option | default ({}) ) }}"
      tags: format-xfs

- name: Format Swift disk excluded options
  hosts: swift_obj
  tasks:
    - shell: |
        mkfs.xfs -L {{ item.split(',')[1] }} -f -i size={{ xfs_inode_size |default('1024') | int }} {{ item.split(',')[0] }}
      with_items: swift_drives.stdout_lines
      when:
        - "{{ swift_drives.stdout_lines | length > 0 }}"
        - "{{ item.split(',')[1] not in ( exclude_drive_labels | default ({}) ) }}"
        - "{{ item.split(',')[1] in ( exclude_drive_labels_format_option | default ({}) ) }}"
      tags: format-xfs

- name: Mount Swift disks
  hosts: swift_obj
  tasks:
    - mount:
        name: "/srv/node/{{ item.split(',')[1] }}"
        src: "LABEL={{ item.split(',')[1] }}"
        fstype: xfs
        opts: "{{ xfs_mount_options |default('rw,noatime,nodiratime,nobarrier,logbufs=8,noquota') }}"
        state: mounted
      with_items: swift_drives.stdout_lines
      when:
        - "{{ swift_drives.stdout_lines | length > 0 }}"
        - "{{ item.split(',')[1] not in ( exclude_drive_labels | default ({}) ) }}"
      tags:
        - "remount"
        - "mount"

- name: Fix Swift Mountpoint permissions
  hosts: swift_obj
  tasks:
    - file:
        name: "/srv/node/{{ item.split(',')[1] }}"
        mode: "0755"
        owner: "swift"
        group: "swift"
      with_items: swift_drives.stdout_lines
      when:
        - "{{ swift_drives.stdout_lines | length > 0 }}"
        - "{{ item.split(',')[1] not in ( exclude_drive_labels | default ({}) ) }}"
      tags: fix-permissions

- name: Start Swift Services
  hosts: swift_obj
  tasks:
    - service:
        name: "{{ item }}"
        state: started
      with_items:
        - "swift-object-server"
        - "swift-object-replicator"
        - "swift-container-reconciler"
        - "swift-object-expirer"
        - "swift-object-updater"
        - "swift-object-auditor"
        - "swift-container-server"
        - "swift-container-replicator"
        - "swift-container-updater"
        - "swift-container-auditor"
        - "swift-account-server"
        - "swift-account-replicator"
        - "swift-account-reaper"
        - "swift-account-auditor"
        - "swift-container-sync"
        - "rsync"
      tags:
        - "service-start"
        - "service-restart"
        - "remount"
