---
# Copyright 2017-Present, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ops_requires_pip_packages:
  - virtualenv

ops_pip_dependencies:
  - python-openstackclient
  - python-neutronclient

ops_apt_util_packages:
  - bash-completion
  - curl
  - dstat
  - htop
  - iotop
  - lsof
  - sudo
  - tcpdump
  - vim
  - screen
  - python-pip

ops_apt_host_packages:
  - openssh-server
  - bridge-utils
  - iptables-persistent
  - linux-crashdump
  - debootstrap
  - lvm2
  - ntp
  - ntpdate
  - vlan
  - python-pip
  - sysfsutils

ops_neutron_debug_packages:
  - iputils-arping
  - ethtool
  - curl


ops_venv: "/openstack/venvs/rcbops-{{ rpc_release }}"
ops_venv_bin: "{{ ops_venv }}/bin"
ops_pip_venv_enabled: True


# kernel modules required on hosts
ops_host_kernel_modules:
  - bonding
  - 8021q

# sysctl parameters required on hosts
ops_host_kernel_sysctl:
  - { key: 'net.ipv4.ip_forward', value: 1 }
  - { key: 'net.ipv4.conf.all.rp_filter', value: 0 }
  - { key: 'net.ipv4.conf.default.rp_filter', value: 0 }

# Which directory is used as OSA config directory
osa_deploy_dir: "/etc/openstack_deploy"
scm_config_dir: "/opt/rpc-config"
scm_osa_dir: "{{ scm_config_dir }}/{{ environment_prefix }}/configs/openstack"
scm_ssh_key_dir: "{{ scm_config_dir }}/{{ environment_prefix }}/configs/ssh"
